ARG EXTEND_FROM_test__subcompo_ness='example-registry.com/test/subcompo:latest'
FROM ${EXTEND_FROM_test__subcompo_ness}

COPY compo1_src ./

COPY compo1_src_1 ./
COPY compo1_src_2 ./
COPY compo1_src_3 ./

RUN sleep 10

